### PR TITLE
fiex[services/contacts/entites.ts]: change of type

### PR DESCRIPTION
**Pull request by Castelblanco**
change the type of custom properties from string to any
[key: string]: string | null
[key: string]: any | null

### CODE REVIEW

**Comment by Castelblanco** [comment]
I wanted to make this change to be able to add phone and email to the contacts when they are created or updated, since in pure text bitrix24 does not receive them, they need this strict:
"param": [
  {
    VALUE_TYPE: 'value',
    VALUE: 'value'
  }
]

**Comment by mrhyde** [comment]
Thank you for your contribution. I will investigate this case and come back to you in a short time

**Comment by mrhyde** [comment]
@Castelblanco can you provide a simple code example of what you trying to achieve? Are you trying to create a new contact using `crm.contact.add` method or update the existing one?

**Comment by mrhyde** [comment]
@Castelblanco this was fixed in c9cdc05cfea2cccdc7b5585c7ff4d23c368af4de and published with version 2.5.0
Please let me know if you have any trouble with it

**Comment by Castelblanco** [comment]
If it works, uninstall the library and reinstall it to verify that everything is native to the library and it works, thank you very much.

**Pull request closed without merging**
